# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E9K6dhuf5ZxgJ74Rzg97pPUDM6X4W3ks
"""

from statsmodels.tsa.stattools import adfuller, pacf, acf
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("AirQualityUCI.csv", sep=';', decimal=',')

# Найти стационарный ряд в AirQualityUCI. Или привести ряд к стационарному.
co = data['CO(GT)'].replace(-200, np.nan).dropna()

def second_task():
  adftest = adfuller(co)
  print('p-value for CO(GT) - ', adftest[1])

  #Использовать модель авторегрессии (AR) для предсказания следующих значений ряда

  #Определить лаг с помощью графика частичной автокорреляционной функции (PACF).
  pacf_value, confint = pacf(co, alpha=0.05) ## надо вспомнить че это делает
  conf_lower = confint[:, 0] - pacf_value
  conf_upper = confint[:, 1] - pacf_value

  lags = []
  for i in range(1, len(pacf_value)):
      if pacf_value[i] < conf_lower[i] or pacf_value[i] > conf_upper[i]:
          lags.append(i)

  best_lag = lags[0] if lags else 1
  print(f'Значимые лаги: {lags[:10]}..., выбран лаг: {best_lag}')
  #Создать и обучить модель AR.

  train_size = int(len(co)*0.8)
  train, test = co[:train_size], co[train_size:]
  model = AutoReg(train, lags=best_lag).fit()
  #print(model.summary())

  # прогноз ar-модели
  pred = model.predict(start=len(train), end=len(train)+len(test)-1)

  # Построить график.
  fig, axes = plt.subplots(2, 1, figsize=(10, 6), sharex=False)
  axes[0].plot(co.values[:800], color='steelblue', lw=0.8)
  axes[0].set_title("Ряд CO(GT) (первые 800 точек)")
  axes[0].grid(alpha=0.3)

  axes[1].plot(test.index, test.values, label="Факт", color='black', lw=0.8)
  axes[1].plot(test.index, pred.values, label="Прогноз AR", color='red', lw=0.8)
  axes[1].set_title("Прогноз vs факт")
  axes[1].legend()
  axes[1].grid(alpha=0.3)

  plt.tight_layout()
  plt.show()

def third_task():
  windows = [3, 5, 10, 50]
  sma_dict = {}
  for w in windows:
    sma_dict[f"SMA_{w}"] = co.rolling(window=w).mean()


  fig, ax = plt.subplots(figsize=(14, 5))
  ax.plot(co.values[:1000], label='Исходный ряд', color='black', lw=0.8, alpha=0.7)

  colors = ['steelblue', 'orange', 'green', 'red']
  for (name, sma), color in zip(sma_dict.items(), colors):
      ax.plot(sma.values[:1000], label=name, color=color, lw=1)

  ax.set_title("Аппроксимация CO(GT) скользящим средним")
  ax.legend()
  ax.grid(alpha=0.3)
  plt.show()

  acf_value, confint = acf(co, alpha=0.05, nlags=50)
  conf_lower = confint[:, 0] - acf_value
  conf_upper = confint[:, 1] - acf_value

  lags = []
  for i in range(1, len(acf_value)):
      if acf_value[i] < conf_lower[i] or acf_value[i] > conf_upper[i]:
          lags.append(i)

  best_lag = lags[0] if lags else 1

  train_size = int(len(co) * 0.8)
  train, test = co[:train_size], co[train_size:]

  ma_model = ARIMA(train, order=(0, 0, best_lag)).fit()
  #print(ma_model.summary())

  pred = ma_model.predict(start=len(train), end=len(train)+len(test)-1)

  fig, ax = plt.subplots(figsize=(14, 5))

  # Исходный ряд
  ax.plot(co.values, label='Исходный ряд', color='steelblue', lw=0.7)

  # Прогноз
  ax.plot(pred.values, label=f'Прогноз MA({best_lag})', color='red', lw=1.5)

  ax.set_title(f"Прогноз модели скользящего среднего MA({best_lag})")
  ax.legend()
  ax.grid(alpha=0.3)
  plt.show()

def fourth_task():
  pacf_vals, pacf_ci = pacf(co, nlags=40, alpha=0.05)
  acf_vals, acf_ci = acf(co, nlags=40, alpha=0.05)

  def first_significant_lag(vals, ci):
    # vals[0]=1 для ACF/PACF, лаги начинаем с 1
    for lag in range(1, len(vals)):
        low = ci[lag, 0]
        high = ci[lag, 1]
        # если 0 вне интервала -> лаг значим
        if not (low <= 0 <= high):
            return lag
    return 1

  p = first_significant_lag(pacf_vals, pacf_ci)
  q = first_significant_lag(acf_vals, acf_ci)
  print(f"Выбраны параметры: p={p}, d={0}, q={q}")

  train_size = int(len(co) * 0.8)
  train = co.iloc[:train_size]
  test = co.iloc[train_size:]

  arima_model = ARIMA(train, order=(p, 0, q)).fit()
  arima_fc = arima_model.get_forecast(steps=len(test))
  arima_pred = arima_fc.predicted_mean
  arima_ci = arima_fc.conf_int()


  # График ARIMA
  plt.figure(figsize=(13, 5))
  plt.plot(train.index, train.values, label='Train', color='steelblue', lw=1)
  plt.plot(test.index, test.values, label='Test (fact)', color='black', lw=1)
  plt.plot(test.index, arima_pred.values, '--', label=f'ARIMA({p},{0},{q}) forecast', color='tomato', lw=1.5)

  # ДИ
  plt.fill_between(
      test.index,
      arima_ci.iloc[:, 0].values,
      arima_ci.iloc[:, 1].values,
      color='tomato', alpha=0.18, label='95% CI'
  )
  plt.title(f'Прогноз ARIMA({p},{0},{q}) для CO(GT)')
  plt.legend()
  plt.grid(alpha=0.3)
  plt.tight_layout()
  plt.show()

if __name__ == "__main__":
  fourth_task()